### ISSUE TITLE
embed dependencies within package.json

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/HLODSystem#75]

**Comment by ZiadJ** [comment]
Is there any reason for it not being able to work out of the box? I've moved on to other things. The installation process is too much of a hassle right now but I'll gladly reconsider once this is fixed.

**Comment by JangkyuSeo** [comment]
Thank you for you guys feedback.
Since this repository uses git-submodule, ssh configuration is required.
When I made it, there was only a way to include the source code, so I managed it using git-submodule.
There seems to be another way now.
Let me check.

**Comment by JangkyuSeo** [comment]
I tried to remove submodule and using dependency package by git repo but PackageManager is not allow this.  Only project level support this behaviour. 

I think landing to PackageManager is only way to simplify installation.
