### ISSUE TITLE
terrain hlod problem

### ISSUE THREAD

**Issue by hulent** [Unity-Technologies/HLODSystem#77]
I try to use terrain hlod, I found that the terrain is converted to many HLOD meshes, but the origin terrain will not be managed by HLOD Controller, it means I can't use the origin terrain. I think it's not good, has other solution?

**Comment by JangkyuSeo** [comment]
TerrainHLOD solution is baking terrain from terrain data and use it. It is not use original terrain on rendering. 
TerrainHLOD was created to solve the problem of not getting enough performance on Mobile. Terrain doesn't allow customize the renderer, so I focus on using data to do a better way of rendering.
So I have no intention of using the original terrain.

**Comment by hulent** [comment]
Got it, thank you.
