### ISSUE TITLE
Streaming load progress

### ISSUE THREAD

**Issue by hulent** [Unity-Technologies/HLODSystem#78]
I just found IsLoadDone function, when I use hlod system to a large scene streaming loading, we need the loading progress.

**Comment by JangkyuSeo** [comment]
Thank you for your feedback.
Let me check.

**Comment by JangkyuSeo** [comment]
You can calculate progress like this:

`loadProgress.maxValue = controller.GetNodeCount();`
`loadProgress.value = controller.GetReadyNodeCount();`
