### ISSUE TITLE
Large scene memory problem

### ISSUE THREAD

**Issue by hulent** [Unity-Technologies/HLODSystem#80]
When baked HLOD in large scene, the origin gameobjects is not removed. So if the origin scene is very large, the memory is still too big, loading time is still too long.

**Comment by JangkyuSeo** [comment]
How big of a terrain do you use?
I don't recommend using large terrain as it is. Using a terrain that is too large will cause a number of issues including memory issues.

I cut the terrain to 500x500 and use an external tool to manage them.

The reason of not deleting the original is you can edit original terrain if you want. But it should be deleted at build time. I missed this part. Thank you for the feedback.

**Comment by hulent** [comment]
Oh, the origin gameobjects will be deleted at building time, perfect! Thank you for your reply.
