### ISSUE TITLE
An error about UnityMeshSimplifier

### ISSUE THREAD

**Issue by JackMoljerc** [Unity-Technologies/HLODSystem#84]
Could you please help me ? I Got the UnityMeshSimplifier from [https://github.com/Unity-Technologies/UnityMeshSimplifier](url) and  installed it .But I still got an error"The type or namespace name 'UnityMeshSimplifier' could not be found in the global namespace (are you missing an assembly reference?".

**Comment by haiyaojing** [comment]
Follow wiki

**Comment by Nichi72** [comment]
I also had the same error. I did improt with Download Zip. However, when I received and applied it with Git, the problem was solved.

**Comment by JangkyuSeo** [comment]
This problem occurs when the submodule is not received.
Please follow the next part of the document.
https://docs.google.com/document/d/18HgBIr8oJweKaXtsIHZlh0s5HuXvQVmVfVcMPHAYS1A/edit#heading=h.m94jf5x0zy4j

I'm closing this issue because it's too old.
