### ISSUE TITLE
'this part' in documentation is not referenced anymore

### ISSUE THREAD

**Issue by smitdylan2001** [Unity-Technologies/HLODSystem#98]
In the documentation there is a referal to 'this section' about the HLOD component, which is not linked anymore

**Comment by JangkyuSeo** [comment]
Thank you for report it. I fixed it.

**Comment by smitdylan2001** [comment]
Great!
Also maybe add a step for adding the HLOD camera to the camera gameobject (or automate this to MainCamera once you add the HLOD module)

**Comment by smitdylan2001** [comment]
Issue was fixed
